# Generated by Django 4.1.1 on 2023-01-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=30)),
                ('f2', models.CharField(max_length=30)),
                ('f3', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MyApps1.base')),
                ('f4', models.CharField(max_length=30)),
            ],
            bases=('MyApps1.base',),
        ),
    ]
