# Generated by Django 4.1.1 on 2023-01-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApps1', '0005_employees'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='employees',
            name='eaddr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employees',
            name='ename',
            field=models.CharField(max_length=50),
        ),
    ]
